config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  devise_for :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p style="color: deepskyblue"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p style="color: red"><%= flash[:alert] %></p>
    <% end %>
    <ul>
      <% if current_user %>
        <li><%= current_user.email %>さん</li>
        <li><%= link_to "アカウント編集", edit_user_registration_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %></li>
      <% else %>
        <li><%= link_to "アカウント登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
    <%= yield %>
    <% if Rails.env.development? %>
      <div style="margin-top: 10px">
        <%= link_to "letter_opener_web", letter_opener_web_path, style: "color: gray; font-size: 12px" %>
      </div>
    <% end %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Hello!</h1>
<p>This is home!</p>